
spring:
  application:
    name: gateway

server:
  port: 8761


eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  dashboard:
    path: /eureka_dash
